// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: error.sql

package db

import (
	"context"
	"database/sql"
)

const insertError = `-- name: InsertError :exec
INSERT INTO error_records (
  timestamp, error_type, error_message, provider_name, region_code, hostname
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertErrorParams struct {
	Timestamp    int64
	ErrorType    string
	ErrorMessage sql.NullString
	ProviderName sql.NullString
	RegionCode   sql.NullString
	Hostname     sql.NullString
}

func (q *Queries) InsertError(ctx context.Context, arg InsertErrorParams) error {
	_, err := q.db.ExecContext(ctx, insertError,
		arg.Timestamp,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.ProviderName,
		arg.RegionCode,
		arg.Hostname,
	)
	return err
}
