// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type ErrorRecord struct {
	ID           int64
	Timestamp    int64
	ErrorType    string
	ErrorMessage sql.NullString
	ProviderName sql.NullString
	RegionCode   sql.NullString
	Hostname     sql.NullString
}

type PingRecord struct {
	ID             int64
	Hostname       string
	Timestamp      int64
	Success        bool
	LatencyMs      sql.NullInt64
	ConnectionType sql.NullString
	ProviderName   sql.NullString
	RegionCode     sql.NullString
}
